### ISSUE TITLE
`filters` not working with `month-picker` enabled

### ISSUE THREAD

**Issue by tmahamadou01** [Vuepic/vue-datepicker#779] opened 2024-03-12 12:22 UTC
**Describe the bug**
When using `month-picker` together with `filters` the filter does not respect the set `filters`.

**To Reproduce**
[Stackblitz](https://stackblitz.com/edit/vuepic-vue-datepicker-ppec1m?file=src%2Fcomponents%2FPlayground.vue)

code:
```javascript
<template>
  <div>
    <Datepicker v-model="date" month-picker :filters="filters" />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import Datepicker from '@vuepic/vue-datepicker';
import '@vuepic/vue-datepicker/dist/main.css';

import { getMonth, addMonths } from 'date-fns';

const date = ref();

const filters = computed(() => {
  const currentDate = new Date();
  return {
    months: Array.from(Array(3).keys()).map((item) =>
      getMonth(addMonths(currentDate, item + 1))
    ),
  };
});
</script>
```

**Expected behavior**
The datePicker should deactivate the dates that are defined in the `filters`, but in my case, when the `month-picker` props is activated, the filter doesn't work.

**Screenshots**
![Capture d’écran 2024-03-12 à 13 19 22](https://github.com/Vuepic/vue-datepicker/assets/11933841/74a9c04a-c8e1-44c2-acd6-d6c3b98e0c54)

**Desktop & mobile (please complete the following information):**
- Browser: Tested with chrome and firefox but probably all browsers.
- Library version: 8.2.0

**Comment by Jasenkoo** [comment] 2024-03-12 17:09
Duplicate of #769

**Closed by Jasenkoo** 2024-03-12 17:09 UTC
Labels: bug, awaiting triage
