### ISSUE TITLE
Range : Set focus on the last date clicked

### ISSUE THREAD

**Issue by LoLouis10** [Vuepic/vue-datepicker#421] opened 2023-06-02 13:25 UTC
**Current behavior**
When selecting the second date of a range, the focus is set to the oldest one.

**To Reproduce**
1. Open the range DatePicker
2. Select a date (e.g.: 2023/05/01)
3. Select a second date (e.g.: 2023/06/20)
4. The focus is set to the first oldest date, in our case  2023/05/01

**Expected behavior**
The focus must be on the last date selected, 2023/06/20 for the example.

**Desktop & mobile (please complete the following information):**
 - Browser: Chrome
 - Library version for this issue 4.5.1

**Comment by Jasenkoo** [comment] 2023-06-02 18:29
This is intended behaviour, the feature to change it will be included in #400

**Closed by Jasenkoo** 2023-06-02 18:29 UTC
Labels: bug
