### ISSUE TITLE
Month Picker adds a month to the value of the date passed to it from the backend

### ISSUE THREAD

**Issue by uevandalla** [Vuepic/vue-datepicker#490] opened 2023-07-17 20:16 UTC
**Describe the bug**
We can select a month just fine, send it to the back end just fine, when we go into edit the record, we pass back the correct month and year however the display adds a month (if December is the selected month it rolls to January but doesn't increase the year)

**To Reproduce**
1. Create a quote with an estimated release date
2. Go into the Quote and click Edit
3. The Estimated release Date is one month ahead of what was selected

**Expected behavior**
I expect the same month/year that the backend passes to be displayed

**Screenshots**
![image](https://github.com/Vuepic/vue-datepicker/assets/137208695/eec293fe-0433-4e20-9e8d-6c8c3108c661)
![image](https://github.com/Vuepic/vue-datepicker/assets/137208695/fd29fe01-d5d2-451b-9ea6-75a2bff33daa)

**Desktop & mobile (please complete the following information):**
 - Browser chrome
 - Library version 4.3.0

**Comment by trompomorsula** [comment] 2023-07-18 11:22
Same Issue!  The correct date is back date, but the input field shows one month more. It always happens in first page load.

<img width="618" alt="Captura de pantalla 2023-07-18 a las 13 20 22" src="https://github.com/Vuepic/vue-datepicker/assets/60506186/6c41c39a-e291-40d6-931f-226df5e3fd7b">

**Comment by trompomorsula** [comment] 2023-08-10 12:24
Hi! There's somenthing new about this? :)

**Comment by Jasenkoo** [comment] 2023-08-10 18:50
Yes, will be included in the next release, hopefully, next weekend.

**Comment by Jasenkoo** [comment] 2023-08-10 18:57
I was trying to replicate the issue, and realized it is not a bug.

Based on @uevandalla  configuration, can't be sure for @trompomorsula , you are setting the `model-type="yy-MM-dd"`, but providing a full year which then can't be parsed properly. To fix this, either change `model-type` to `yyyy-MM-dd` or provide year like `23` instead of `2023`

**Closed by Jasenkoo** 2023-08-10 18:57 UTC
Labels: bug

**Comment by trompomorsula** [comment] 2023-08-11 06:44
Sorry, I change that and it still doesn't working...
This is my code:
`<Datepicker 
              v-model="dateModel" 
               model-type="yyyy-MM-dd"
              :range="true" 
              :clearable="false"
              :month-picker="true"
              :dark="true"
              :format-locale="es"
              locale="es"
              cancelText="Cancelar" 
              selectText="Aceptar"
              @update:model-value="setDate"
              class="mr-0 lg:mr-6"
            />`

**Comment by trompomorsula** [comment] 2023-08-11 07:14
Ok, I fix the problem. the problem was the v-model. I passed month like "MM" and now I pass "MMM".
